@base_url = http://localhost:3333
@access_token = {{authenticate_account.response.body.access_token}}

# @name create_account  

POST {{base_url}}/clients/new
Content-Type: application/json

{
  "name": "test",
  "email": "test@email.com",
  "password": "123456"
}

###

# @name authenticate_account

POST {{base_url}}/clients/auth
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "123456"
}

###

# @name get_client_by_id

GET {{base_url}}/clients/me
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

# @name edit_client

PUT {{base_url}}/clients/me/edit
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "test-edited",
  "email": "test@email.com",
  "password": "123456"
}

###

# @name delete_client_by_id

DELETE {{base_url}}/clients/me/delete
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

# @name create_habit

POST {{base_url}}/habits/new
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "title": "Ir para o mercado",
  "weekDays": [0,4,5]
}

###

# @name fetch_habits_by_day

GET {{base_url}}/habits/day
Content-Type: application/json
Authorization: Bearer {{access_token}} 

###

# @name toggle_habit

PATCH {{base_url}}/habits/6a557e55-58ec-4991-8174-4efd1f1e43db/toggle
Content-Type: application/json
Authorization: Bearer {{access_token}}

