@base_url = http://localhost:3333
@access_token = {{authenticate_account.response.body.access_token}}

# @name create_account  

POST {{base_url}}/clients/new
Content-Type: application/json

{
  "name": "test",
  "email": "test@email.com",
  "password": "123456"
}

###

# @name authenticate_account

POST {{base_url}}/clients/auth
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "123456"
}

###

# @name get_client_by_id

GET {{base_url}}/clients/me
Content-Type: application/json
Authorization: Bearer {{access_token}}