name: "CI"

on:
  push:

env:
  DATABASE_URL: postgresql://user:password@postgresDB:5432/db
  JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
  JWT_PUBLIC_KEY: ${{ secrets.JWT_PUBLIC_KEY }}

jobs:

  tests:
      name: Run Tests 
      runs-on: ubuntu-latest
      container: node:20-bookworm-slim

      services:
        postgresDB:
          image: postgres
          env:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: db
          ports:
            - 5432:5432

      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up Node.js | Node 20
          uses: actions/setup-node@v4
          with:
            node-version: 20

        - name: Install pnpm manager
          run: npm install -g pnpm

        - name: Install dependencies
          run: pnpm install
  
        - name: Run Unit Tests
          run: pnpm run test

        - name: Generate Prisma Client
          env:
            DATABASE_URL: postgresql://user:password@postgresDB:5432/db?schema=public
          run: pnpm prisma generate
        
        - name: Instalar OpenSSL
          run: apt-get update -y && apt-get install -y openssl

        - name: Run Migrations
          env:
            DATABASE_URL: postgresql://user:password@postgresDB:5432/db?schema=public
          run: pnpm prisma migrate deploy

        - name: Run End-to-End Tests
          run: pnpm run test:e2e